# Generated by Django 4.2.7 on 2023-11-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('auto', models.CharField(max_length=200)),
                ('cantidad_disponible', models.IntegerField()),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'libro',
            },
        ),
    ]
