# Generated by Django 4.2.7 on 2023-11-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prestamo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='auto',
            new_name='autor',
        ),
    ]
