# Generated by Django 4.2.7 on 2023-11-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_prestamo_confirmado_prestamo_reservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='devuelto',
            field=models.BooleanField(null=True),
        ),
    ]
